### PR TITLE
Support GHC 9

### PR DESCRIPTION
**Pull request by ncfavier**
Diff best viewed with "hide whitespace" on.

### CODE REVIEW

**Comment by cafce25** [comment]
Not sure if it is your patch or something I'm not getting but compiling with this PR applied gives me a `dice` binary that always produces the same output.

i.e. `dice d10` always results in `7` for me.
I can't get this to compile without these changes though so I can't tell if it's introduced by this or if it's some other issue in my build system/setup.

**Comment by ncfavier** [comment]
You're right, I'm an idiot and didn't bother to test this. ~Should be `createSystemRandom`, not `create`.~

I ended up using `newStdGen` and `newIOGenM` from `random` instead of `mwc-random`.

**Comment by ncfavier** [comment]
Fixed the lambdabot PR as well.

**Comment by Bodigrim** [comment]
@int-e any chance to merge this? It would be great to unblock GHC 9.0 and 9.2, there is already Stackage LTS and nightly.

**Comment by Bodigrim** [comment]
@int-e @ncfavier any news on this?

**Comment by ncfavier** [comment]
I asked to get maintainer access to dice and lambdabot so I could take care of this, didn't get a response. I'll follow https://wiki.haskell.org/Taking_over_a_package#If_you_cannot_contact_the_author/maintainer soon.

**Comment by ncfavier** [comment]
Released [dice 0.1.1](https://hackage.haskell.org/package/dice-0.1.1).

**Pull request closed without merging**
